<div class="sectionTitle">
	Table Selector
</div>

<div class="sectionWrapper">
	<div class="sectionInfo">
		Please select a table to compare.  These are the tables associated with the loaded configuration.  Each table also shows how many rows are out of sync.
	</div>
</div>

<div class="diffGenerator">
	<div class="generatorLink">
		<a href="javascript:void(0);" id="ajaxGenerateLink">Generate Diffs</a>
	</div>
	<div class="generatorOutput" id="generatorOutputID">

	</div>
</div>

<div class="tableContainer" id="tableContainerID">

	<ul>

	<?php foreach ($this->tableList as $table): ?>

		<li>
			<a href="/compare/tables/name/<?php echo $table['name']; ?>">
				<span class="tableLink"><?php echo $table['name']; ?></span>
			</a> 
			<span class="tableCount">[ <?php echo $table['count']; ?> rows ]</span>
		</li>

	<?php endforeach ?>

	</ul>

</div>

<script type="text/javascript">


$(document).ready(function(){

    /**
     * Handler for the MC Lookup function.
     */
    $("#ajaxGenerateLink").click(function (){
        generateDiffs();
    });
});

/**
 *
 *
 *
 */
function generateDiffs()
{
    // Set up the loading placeholder.
    var loadingPlaceholder = '<center><span><img src="' + baseUrl + '/images/ajax-loader.gif"></span></center>';
    $('#generatorOutputID').html(loadingPlaceholder);
    $('#generatorOutputID').css("display", "block");

    // Make an AJAX request to validate the MC Number.
    $.ajax({
        
            type: 'POST',
            dataType: 'json',
            url: baseUrl + '/ajax/runcli',
            async: true,

            // Params to pass to the AJAX controller.
            data: { },
            success: function(json) {

                var status = json['status'];

                if (status === "VALID") {
                    $('#generatorOutputID').html(json['output']);
                    $('#tableContainerID').html(json['refresh']);
                } else {
                    $('#generatorOutputID').html("There was an error");
                }
            }
    });
}

</script>